/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package molemap;

import javax.swing.JOptionPane;

/**
 *
 * @author hickey705
 */
public class MoleFrame extends javax.swing.JFrame
{

    private PeriodTable periodicTable = new PeriodTable();

    /**
     * Creates new form MoleFrame
     */
    public MoleFrame()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem83 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        gramsButton = new javax.swing.JButton();
        molesButton = new javax.swing.JButton();
        volumeButton = new javax.swing.JButton();
        atomButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenuItem43 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem44 = new javax.swing.JMenuItem();
        jMenuItem45 = new javax.swing.JMenuItem();
        jMenuItem46 = new javax.swing.JMenuItem();
        jMenuItem47 = new javax.swing.JMenuItem();
        jHydrogenButton = new javax.swing.JMenuItem();
        jMenuItem49 = new javax.swing.JMenuItem();
        jMenuItem50 = new javax.swing.JMenuItem();
        jMenuItem51 = new javax.swing.JMenuItem();
        jMenuItem52 = new javax.swing.JMenuItem();
        jMenuItem53 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem58 = new javax.swing.JMenuItem();
        jMenuItem59 = new javax.swing.JMenuItem();
        jMenuItem60 = new javax.swing.JMenuItem();
        jMenuItem61 = new javax.swing.JMenuItem();
        jMenuItem62 = new javax.swing.JMenuItem();
        jMenuItem63 = new javax.swing.JMenuItem();
        jMenuItem64 = new javax.swing.JMenuItem();
        jMenuItem65 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem66 = new javax.swing.JMenuItem();
        jMenuItem67 = new javax.swing.JMenuItem();
        jMenuItem68 = new javax.swing.JMenuItem();
        jMenuItem69 = new javax.swing.JMenuItem();
        jMenuItem70 = new javax.swing.JMenuItem();
        jMenuItem71 = new javax.swing.JMenuItem();
        jMenuItem72 = new javax.swing.JMenuItem();
        jMenuItem73 = new javax.swing.JMenuItem();
        jMenuItem74 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem54 = new javax.swing.JMenuItem();
        jMenuItem55 = new javax.swing.JMenuItem();
        jMenuItem56 = new javax.swing.JMenuItem();
        jMenuItem57 = new javax.swing.JMenuItem();
        jMenuItem79 = new javax.swing.JMenuItem();
        jMenuItem80 = new javax.swing.JMenuItem();
        jMenuItem81 = new javax.swing.JMenuItem();
        jMenuItem82 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem84 = new javax.swing.JMenuItem();
        jMenuItem85 = new javax.swing.JMenuItem();
        jMenuItem86 = new javax.swing.JMenuItem();
        jMenuItem87 = new javax.swing.JMenuItem();
        jMenuItem88 = new javax.swing.JMenuItem();
        jMenuItem89 = new javax.swing.JMenuItem();
        jMenuItem90 = new javax.swing.JMenuItem();
        jMenuItem91 = new javax.swing.JMenuItem();
        jMenuItem92 = new javax.swing.JMenuItem();
        jMenuItem93 = new javax.swing.JMenuItem();
        jMenuItem94 = new javax.swing.JMenuItem();
        jMenuItem95 = new javax.swing.JMenuItem();
        jMenuItem96 = new javax.swing.JMenuItem();
        jMenuItem97 = new javax.swing.JMenuItem();
        jMenuItem98 = new javax.swing.JMenuItem();
        jMenuItem99 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem75 = new javax.swing.JMenuItem();
        jMenuItem76 = new javax.swing.JMenuItem();
        jMenuItem77 = new javax.swing.JMenuItem();
        jMenuItem78 = new javax.swing.JMenuItem();
        jMenuItem100 = new javax.swing.JMenuItem();
        jMenuItem101 = new javax.swing.JMenuItem();
        jMenuItem102 = new javax.swing.JMenuItem();
        jMenuItem103 = new javax.swing.JMenuItem();
        jMenuItem104 = new javax.swing.JMenuItem();
        jMenuItem105 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem106 = new javax.swing.JMenuItem();
        jMenuItem107 = new javax.swing.JMenuItem();
        jMenuItem108 = new javax.swing.JMenuItem();
        jMenuItem109 = new javax.swing.JMenuItem();
        jMenuItem110 = new javax.swing.JMenuItem();
        jMenuItem111 = new javax.swing.JMenuItem();
        jMenuItem112 = new javax.swing.JMenuItem();
        jMenuItem113 = new javax.swing.JMenuItem();
        jMenuItem114 = new javax.swing.JMenuItem();
        jMenuItem115 = new javax.swing.JMenuItem();
        jMenuItem116 = new javax.swing.JMenuItem();
        jMenuItem117 = new javax.swing.JMenuItem();
        jMenuItem118 = new javax.swing.JMenuItem();
        jMenuItem119 = new javax.swing.JMenuItem();
        jMenuItem120 = new javax.swing.JMenuItem();
        jMenuItem121 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem18.setText("jMenuItem18");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenu8.setText("jMenu8");

        jMenuItem83.setText("jMenuItem83");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setText("Volume (l)");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel3.setText("Moles");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel4.setText("Atoms");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel5.setText("Grams");

        gramsButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                gramsButtonActionPerformed(evt);
            }
        });

        molesButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        molesButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                molesButtonActionPerformed(evt);
            }
        });

        volumeButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        volumeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                volumeButtonActionPerformed(evt);
            }
        });

        atomButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        atomButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                atomButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("* 22.4");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel12.setText("/ 22.4");

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel13.setText("*  (6.002 * 10^24)");

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel14.setText("/  (6.002 * 10^24)");

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel15.setText("->");

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel17.setText("<-");

        jLabel6.setFont(new java.awt.Font("Lucida Fax", 1, 13)); // NOI18N
        jLabel6.setText("^");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setText("V");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel8.setText("* Formula Mass");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel9.setText("/ Formula Mass");

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel18.setText("<-");

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel19.setText("->");

        jMenu2.setText("A-B");

        jMenuItem17.setText("Actinium");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem17);

        jMenuItem16.setText("Aluminum");
        jMenu2.add(jMenuItem16);

        jMenuItem14.setText("Americium");
        jMenu2.add(jMenuItem14);

        jMenuItem15.setText("Antiomy");
        jMenu2.add(jMenuItem15);

        jMenuItem13.setText("Argon");
        jMenu2.add(jMenuItem13);

        jMenuItem12.setText("Arsenic");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuItem11.setText("Astatine");
        jMenu2.add(jMenuItem11);

        jMenuItem10.setText("Barium");
        jMenu2.add(jMenuItem10);

        jMenuItem9.setText("Berkelium");
        jMenu2.add(jMenuItem9);

        jMenuItem8.setText("Beryllium");
        jMenu2.add(jMenuItem8);

        jMenuItem7.setText("Bismuth");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem6.setText("Bohrium");
        jMenu2.add(jMenuItem6);

        jMenuItem5.setText("Boron");
        jMenu2.add(jMenuItem5);

        jMenuItem2.setText("Bromine");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("C");

        jMenuItem19.setText("Cadmium");
        jMenu1.add(jMenuItem19);

        jMenuItem20.setText("Calcium");
        jMenu1.add(jMenuItem20);

        jMenuItem21.setText("Californium");
        jMenu1.add(jMenuItem21);

        jMenuItem22.setText("Carbon");
        jMenu1.add(jMenuItem22);

        jMenuItem23.setText("Cerium");
        jMenu1.add(jMenuItem23);

        jMenuItem24.setText("Cesium");
        jMenu1.add(jMenuItem24);

        jMenuItem25.setText("Chlorine");
        jMenu1.add(jMenuItem25);

        jMenuItem26.setText("Chromium");
        jMenu1.add(jMenuItem26);

        jMenuItem27.setText("Cobalt");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem27);

        jMenuItem28.setText("Copper");
        jMenu1.add(jMenuItem28);

        jMenuItem29.setText("Curium");
        jMenu1.add(jMenuItem29);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("D-G");

        jMenuItem4.setText("Darmstadtium");
        jMenu3.add(jMenuItem4);

        jMenuItem33.setText("Dubnium");
        jMenu3.add(jMenuItem33);

        jMenuItem34.setText("Dysprosium");
        jMenu3.add(jMenuItem34);

        jMenuItem35.setText("Einsteinium");
        jMenu3.add(jMenuItem35);

        jMenuItem36.setText("Erbium");
        jMenu3.add(jMenuItem36);

        jMenuItem37.setText("Europium");
        jMenu3.add(jMenuItem37);

        jMenuItem38.setText("Fluorine");
        jMenu3.add(jMenuItem38);

        jMenuItem39.setText("Francium");
        jMenu3.add(jMenuItem39);

        jMenuItem40.setText("Gadolinium");
        jMenu3.add(jMenuItem40);

        jMenuItem41.setText("Gallium");
        jMenu3.add(jMenuItem41);

        jMenuItem42.setText("Germanium");
        jMenu3.add(jMenuItem42);

        jMenuItem43.setText("Gold");
        jMenu3.add(jMenuItem43);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("H-K");

        jMenuItem44.setText("Hafnium");
        jMenu6.add(jMenuItem44);

        jMenuItem45.setText("Hassium");
        jMenu6.add(jMenuItem45);

        jMenuItem46.setText("Helium");
        jMenuItem46.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem46ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem46);

        jMenuItem47.setText("Holmium");
        jMenuItem47.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem47ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem47);

        jHydrogenButton.setText("Hydrogen");
        jHydrogenButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jHydrogenButtonActionPerformed(evt);
            }
        });
        jMenu6.add(jHydrogenButton);

        jMenuItem49.setText("Indium");
        jMenu6.add(jMenuItem49);

        jMenuItem50.setText("Iodine");
        jMenu6.add(jMenuItem50);

        jMenuItem51.setText("Iridium");
        jMenu6.add(jMenuItem51);

        jMenuItem52.setText("Iron");
        jMenu6.add(jMenuItem52);

        jMenuItem53.setText("Krypton");
        jMenu6.add(jMenuItem53);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("L-M");

        jMenuItem30.setText("Lanthanum");
        jMenu7.add(jMenuItem30);

        jMenuItem31.setText("Lawrencium");
        jMenu7.add(jMenuItem31);

        jMenuItem32.setText("Lead");
        jMenu7.add(jMenuItem32);

        jMenuItem58.setText("Lithium");
        jMenu7.add(jMenuItem58);

        jMenuItem59.setText("Lutetium");
        jMenu7.add(jMenuItem59);

        jMenuItem60.setText("Magnesium");
        jMenu7.add(jMenuItem60);

        jMenuItem61.setText("Manganese");
        jMenu7.add(jMenuItem61);

        jMenuItem62.setText("Meitnerium");
        jMenu7.add(jMenuItem62);

        jMenuItem63.setText("Mendelevium");
        jMenu7.add(jMenuItem63);

        jMenuItem64.setText("Mercury");
        jMenu7.add(jMenuItem64);

        jMenuItem65.setText("Molybdenum");
        jMenu7.add(jMenuItem65);

        jMenuBar1.add(jMenu7);

        jMenu9.setText("N-O");

        jMenuItem66.setText("Neodymium");
        jMenu9.add(jMenuItem66);

        jMenuItem67.setText("Neon");
        jMenu9.add(jMenuItem67);

        jMenuItem68.setText("Neptumium");
        jMenu9.add(jMenuItem68);

        jMenuItem69.setText("Nickel");
        jMenu9.add(jMenuItem69);

        jMenuItem70.setText("Niobium");
        jMenu9.add(jMenuItem70);

        jMenuItem71.setText("Nitrogen");
        jMenuItem71.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem71ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem71);

        jMenuItem72.setText("Nobelium");
        jMenu9.add(jMenuItem72);

        jMenuItem73.setText("Osmium");
        jMenu9.add(jMenuItem73);

        jMenuItem74.setText("Oxygen");
        jMenu9.add(jMenuItem74);

        jMenuBar1.add(jMenu9);

        jMenu10.setText("P");

        jMenuItem54.setText("Palladium");
        jMenu10.add(jMenuItem54);

        jMenuItem55.setText("Phosphorus");
        jMenu10.add(jMenuItem55);

        jMenuItem56.setText("Platinum");
        jMenu10.add(jMenuItem56);

        jMenuItem57.setText("Polonium");
        jMenu10.add(jMenuItem57);

        jMenuItem79.setText("Potassium");
        jMenu10.add(jMenuItem79);

        jMenuItem80.setText("Praseodymium");
        jMenu10.add(jMenuItem80);

        jMenuItem81.setText("Promethium");
        jMenu10.add(jMenuItem81);

        jMenuItem82.setText("Protactinium");
        jMenu10.add(jMenuItem82);

        jMenuBar1.add(jMenu10);

        jMenu11.setText("R-S");

        jMenuItem84.setText("Radium");
        jMenu11.add(jMenuItem84);

        jMenuItem85.setText("Radon");
        jMenu11.add(jMenuItem85);

        jMenuItem86.setText("Rhenium");
        jMenu11.add(jMenuItem86);

        jMenuItem87.setText("Rhodium");
        jMenu11.add(jMenuItem87);

        jMenuItem88.setText("Rubidium");
        jMenu11.add(jMenuItem88);

        jMenuItem89.setText("Ruthenium");
        jMenu11.add(jMenuItem89);

        jMenuItem90.setText("Rutherfordium");
        jMenuItem90.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem90ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem90);

        jMenuItem91.setText("Samarium");
        jMenu11.add(jMenuItem91);

        jMenuItem92.setText("Scandium");
        jMenu11.add(jMenuItem92);

        jMenuItem93.setText("Seaborgium");
        jMenu11.add(jMenuItem93);

        jMenuItem94.setText("Selenium");
        jMenu11.add(jMenuItem94);

        jMenuItem95.setText("Silicon");
        jMenu11.add(jMenuItem95);

        jMenuItem96.setText("Silver");
        jMenu11.add(jMenuItem96);

        jMenuItem97.setText("Sodium");
        jMenu11.add(jMenuItem97);

        jMenuItem98.setText("Strontium");
        jMenu11.add(jMenuItem98);

        jMenuItem99.setText("Sulfer");
        jMenu11.add(jMenuItem99);

        jMenuBar1.add(jMenu11);

        jMenu12.setText("T");

        jMenuItem75.setText("Tantalum");
        jMenu12.add(jMenuItem75);

        jMenuItem76.setText("Technetium");
        jMenu12.add(jMenuItem76);

        jMenuItem77.setText("Tellurium");
        jMenu12.add(jMenuItem77);

        jMenuItem78.setText("Terbium");
        jMenu12.add(jMenuItem78);

        jMenuItem100.setText("Thallium");
        jMenu12.add(jMenuItem100);

        jMenuItem101.setText("Thorium");
        jMenu12.add(jMenuItem101);

        jMenuItem102.setText("Thulium");
        jMenu12.add(jMenuItem102);

        jMenuItem103.setText("Tin");
        jMenuItem103.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem103ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem103);

        jMenuItem104.setText("Titanium");
        jMenu12.add(jMenuItem104);

        jMenuItem105.setText("Tungsten");
        jMenu12.add(jMenuItem105);

        jMenuBar1.add(jMenu12);

        jMenu13.setText("U-Z");

        jMenuItem106.setText("Ununbium");
        jMenu13.add(jMenuItem106);

        jMenuItem107.setText("Ununhexium");
        jMenu13.add(jMenuItem107);

        jMenuItem108.setText("Ununoctium");
        jMenuItem108.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem108ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem108);

        jMenuItem109.setText("Ununpentium");
        jMenu13.add(jMenuItem109);

        jMenuItem110.setText("Ununquadium");
        jMenu13.add(jMenuItem110);

        jMenuItem111.setText("Ununseptium");
        jMenu13.add(jMenuItem111);

        jMenuItem112.setText("Ununtrium");
        jMenu13.add(jMenuItem112);

        jMenuItem113.setText("Ununium");
        jMenu13.add(jMenuItem113);

        jMenuItem114.setText("Uranium");
        jMenu13.add(jMenuItem114);

        jMenuItem115.setText("Uranium");
        jMenu13.add(jMenuItem115);

        jMenuItem116.setText("Vanadium");
        jMenu13.add(jMenuItem116);

        jMenuItem117.setText("Xenon");
        jMenuItem117.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem117ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem117);

        jMenuItem118.setText("Ytterbium");
        jMenu13.add(jMenuItem118);

        jMenuItem119.setText("Yttrium");
        jMenu13.add(jMenuItem119);

        jMenuItem120.setText("Zinc");
        jMenu13.add(jMenuItem120);

        jMenuItem121.setText("Zirconium");
        jMenu13.add(jMenuItem121);

        jMenuBar1.add(jMenu13);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gramsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(2, 2, 2)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(molesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(108, 108, 108)
                                    .addComponent(jLabel7))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addComponent(jLabel6)
                                    .addGap(104, 104, 104)
                                    .addComponent(jLabel12))))
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addComponent(jLabel15)
                        .addGap(12, 12, 12)
                        .addComponent(atomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(198, 198, 198)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(110, 110, 110))))
            .addGroup(layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(volumeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volumeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gramsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(molesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel19)))
                    .addComponent(atomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volumeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_volumeButtonActionPerformed
    {//GEN-HEADEREND:event_volumeButtonActionPerformed
        numberOfLiters = JOptionPane.showInputDialog("Enter the new number of Liters");
        isLitersSelected = true;
        updateUI();


    }//GEN-LAST:event_volumeButtonActionPerformed

    private void gramsButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_gramsButtonActionPerformed
    {//GEN-HEADEREND:event_gramsButtonActionPerformed
        numberOfGrams = JOptionPane.showInputDialog("Enter the new number of Grams");
        updateUI();
    }//GEN-LAST:event_gramsButtonActionPerformed

    private void molesButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_molesButtonActionPerformed
    {//GEN-HEADEREND:event_molesButtonActionPerformed
        numberOfMoles = JOptionPane.showInputDialog("Enter the new number of Moles");
        isMolesSelected = true;
        updateUI();
    }//GEN-LAST:event_molesButtonActionPerformed

    private void atomButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_atomButtonActionPerformed
    {//GEN-HEADEREND:event_atomButtonActionPerformed
        numberOfAtomsDecimal = JOptionPane.showInputDialog("Enter the decimal of the new number of Atoms");
        numberOfAtomsTens = JOptionPane.showInputDialog("Enter the exponet of the new number of Atoms. Enter the exponet above the ten.");
        isAtomSelected = true;
        updateUI();
    }//GEN-LAST:event_atomButtonActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem2ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem17ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem12ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem7ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem27ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem46ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem46ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem46ActionPerformed
        currElement = periodicTable.getElement(2);
        updateUI();
    }//GEN-LAST:event_jMenuItem46ActionPerformed

    private void jMenuItem71ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem71ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem71ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem71ActionPerformed

    private void jMenuItem90ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem90ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem90ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem90ActionPerformed

    private void jMenuItem103ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem103ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem103ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem103ActionPerformed

    private void jMenuItem108ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem108ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem108ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem108ActionPerformed

    private void jMenuItem117ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem117ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem117ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem117ActionPerformed

    private void jHydrogenButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jHydrogenButtonActionPerformed
    {//GEN-HEADEREND:event_jHydrogenButtonActionPerformed
        currElement = periodicTable.getElement(1);
        updateUI();

    }//GEN-LAST:event_jHydrogenButtonActionPerformed

    private void jMenuItem47ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem47ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem47ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MoleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MoleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MoleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MoleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MoleFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atomButton;
    private javax.swing.JButton gramsButton;
    private javax.swing.JMenuItem jHydrogenButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem100;
    private javax.swing.JMenuItem jMenuItem101;
    private javax.swing.JMenuItem jMenuItem102;
    private javax.swing.JMenuItem jMenuItem103;
    private javax.swing.JMenuItem jMenuItem104;
    private javax.swing.JMenuItem jMenuItem105;
    private javax.swing.JMenuItem jMenuItem106;
    private javax.swing.JMenuItem jMenuItem107;
    private javax.swing.JMenuItem jMenuItem108;
    private javax.swing.JMenuItem jMenuItem109;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem110;
    private javax.swing.JMenuItem jMenuItem111;
    private javax.swing.JMenuItem jMenuItem112;
    private javax.swing.JMenuItem jMenuItem113;
    private javax.swing.JMenuItem jMenuItem114;
    private javax.swing.JMenuItem jMenuItem115;
    private javax.swing.JMenuItem jMenuItem116;
    private javax.swing.JMenuItem jMenuItem117;
    private javax.swing.JMenuItem jMenuItem118;
    private javax.swing.JMenuItem jMenuItem119;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem120;
    private javax.swing.JMenuItem jMenuItem121;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem43;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem45;
    private javax.swing.JMenuItem jMenuItem46;
    private javax.swing.JMenuItem jMenuItem47;
    private javax.swing.JMenuItem jMenuItem49;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem50;
    private javax.swing.JMenuItem jMenuItem51;
    private javax.swing.JMenuItem jMenuItem52;
    private javax.swing.JMenuItem jMenuItem53;
    private javax.swing.JMenuItem jMenuItem54;
    private javax.swing.JMenuItem jMenuItem55;
    private javax.swing.JMenuItem jMenuItem56;
    private javax.swing.JMenuItem jMenuItem57;
    private javax.swing.JMenuItem jMenuItem58;
    private javax.swing.JMenuItem jMenuItem59;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem60;
    private javax.swing.JMenuItem jMenuItem61;
    private javax.swing.JMenuItem jMenuItem62;
    private javax.swing.JMenuItem jMenuItem63;
    private javax.swing.JMenuItem jMenuItem64;
    private javax.swing.JMenuItem jMenuItem65;
    private javax.swing.JMenuItem jMenuItem66;
    private javax.swing.JMenuItem jMenuItem67;
    private javax.swing.JMenuItem jMenuItem68;
    private javax.swing.JMenuItem jMenuItem69;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem70;
    private javax.swing.JMenuItem jMenuItem71;
    private javax.swing.JMenuItem jMenuItem72;
    private javax.swing.JMenuItem jMenuItem73;
    private javax.swing.JMenuItem jMenuItem74;
    private javax.swing.JMenuItem jMenuItem75;
    private javax.swing.JMenuItem jMenuItem76;
    private javax.swing.JMenuItem jMenuItem77;
    private javax.swing.JMenuItem jMenuItem78;
    private javax.swing.JMenuItem jMenuItem79;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem80;
    private javax.swing.JMenuItem jMenuItem81;
    private javax.swing.JMenuItem jMenuItem82;
    private javax.swing.JMenuItem jMenuItem83;
    private javax.swing.JMenuItem jMenuItem84;
    private javax.swing.JMenuItem jMenuItem85;
    private javax.swing.JMenuItem jMenuItem86;
    private javax.swing.JMenuItem jMenuItem87;
    private javax.swing.JMenuItem jMenuItem88;
    private javax.swing.JMenuItem jMenuItem89;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItem90;
    private javax.swing.JMenuItem jMenuItem91;
    private javax.swing.JMenuItem jMenuItem92;
    private javax.swing.JMenuItem jMenuItem93;
    private javax.swing.JMenuItem jMenuItem94;
    private javax.swing.JMenuItem jMenuItem95;
    private javax.swing.JMenuItem jMenuItem96;
    private javax.swing.JMenuItem jMenuItem97;
    private javax.swing.JMenuItem jMenuItem98;
    private javax.swing.JMenuItem jMenuItem99;
    private javax.swing.JButton molesButton;
    private javax.swing.JButton volumeButton;
    // End of variables declaration//GEN-END:variables
    private String numberOfAtomsDecimal;
    private String numberOfLiters;
    private String numberOfMoles;
    private String numberOfGrams;
    private boolean isAtomSelected;
    private boolean isLitersSelected;
    private boolean isMolesSelected;
    private boolean isGramsSelected;
    private double atomsDouble;
    private String numberOfAtomsTens;
    private Elements currElement = periodicTable.getElement(1);

    private void updateUI()
    {
        if (isMolesSelected == true)
        {
            molesButton.setText(numberOfMoles);
            volumeButton.setText(Double.toString((double) (Double.parseDouble(numberOfMoles) * 22.4)));
            atomButton.setText(Double.toString((double) (Double.parseDouble(numberOfMoles) * 6.022 * Math.pow(10, 24))));
            gramsButton.setText(Double.toString((double) currElement.getMass() * Double.parseDouble(numberOfMoles)));
            isMolesSelected = false;

        } else if (isLitersSelected == true)
        {
            volumeButton.setText(String.valueOf(numberOfLiters));
            Double moles = (double) (Double.parseDouble(numberOfLiters) / 22.4);
            molesButton.setText(Double.toString(moles));
            atomButton.setText(Double.toString((double) (moles * 6.022 * Math.pow(10, 24))));
            gramsButton.setText(Double.toString((double) currElement.getMass() * moles));
            isLitersSelected = false;

        } else if (isAtomSelected == true) {
            Double atoms = ((double) ((double) Double.parseDouble(numberOfAtomsDecimal) * Math.pow(10, Double.parseDouble(numberOfAtomsTens))));
            atomButton.setText(Double.toString(atoms));
            Double moles = (double) ((double) atoms / (6.022 * Math.pow(10, 24)));
            molesButton.setText(Double.toString(moles));
            volumeButton.setText(Double.toString((double) (moles * 22.4)));
            gramsButton.setText(Double.toString((double) currElement.getMass() * moles));
            isAtomSelected = false;

        } else {

        //atomButton.setText(String.valueOf(numberOfAtoms));
            //gramsButton.setText(String.valueOf(numberOfGrams));
            //volumeButton.setText(String.valueOf(numberOfLiters));
            //molesButton.setText(String.valueOf(numberOfMoles));
        }
    }
}
